// <auto-generated />
using System;
using Logging.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Logging.Infrastructure.Migrations
{
    [DbContext(typeof(LoggingDbContext))]
    [Migration("20260322093310_InitLoggingDb")]
    partial class InitLoggingDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Logging.Domain.Entities.ActivityLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<byte>("ActionType")
                        .HasColumnType("smallint");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp")
                        .IsDescending()
                        .HasDatabaseName("IX_ActivityLogs_Timestamp");

                    b.ToTable("ActivityLogs", (string)null);
                });

            modelBuilder.Entity("Logging.Domain.Entities.LogChange", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("ActivityLogId")
                        .HasColumnType("uuid");

                    b.Property<string>("Field")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NewCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NewId")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("NewValue")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("OldCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("OldId")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("OldValue")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<byte?>("Type")
                        .HasColumnType("smallint")
                        .HasColumnName("Type");

                    b.HasKey("Id");

                    b.HasIndex("ActivityLogId")
                        .HasDatabaseName("IX_LogChanges_ActivityLogId");

                    b.HasIndex("Field", "NewId")
                        .HasDatabaseName("IX_LogChanges_Field_NewId")
                        .HasFilter("\"NewId\" IS NOT NULL");

                    b.HasIndex("Field", "OldId")
                        .HasDatabaseName("IX_LogChanges_Field_OldId")
                        .HasFilter("\"OldId\" IS NOT NULL");

                    b.ToTable("LogChanges", (string)null);
                });

            modelBuilder.Entity("Logging.Domain.Entities.ActivityLog", b =>
                {
                    b.OwnsOne("Logging.Domain.Entities.LogActor", "Actor", b1 =>
                        {
                            b1.Property<Guid>("ActivityLogId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<string>("AvatarUrl")
                                .HasMaxLength(2048)
                                .HasColumnType("character varying(2048)")
                                .HasColumnName("ActorAvatarUrl");

                            b1.Property<string>("Code")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("ActorCode");

                            b1.Property<string>("Id")
                                .IsRequired()
                                .HasMaxLength(450)
                                .HasColumnType("character varying(450)")
                                .HasColumnName("ActorId");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)")
                                .HasColumnName("ActorName");

                            b1.HasKey("ActivityLogId");

                            b1.HasIndex("Id")
                                .HasDatabaseName("IX_ActivityLogs_ActorId");

                            b1.ToTable("ActivityLogs");

                            b1.WithOwner()
                                .HasForeignKey("ActivityLogId");
                        });

                    b.OwnsOne("Logging.Domain.Entities.LogTarget", "Target", b1 =>
                        {
                            b1.Property<Guid>("ActivityLogId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<string>("Code")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("TargetCode");

                            b1.Property<string>("Id")
                                .IsRequired()
                                .HasMaxLength(450)
                                .HasColumnType("character varying(450)")
                                .HasColumnName("TargetId");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)")
                                .HasColumnName("TargetName");

                            b1.Property<byte>("Type")
                                .HasColumnType("smallint")
                                .HasColumnName("TargetType");

                            b1.HasKey("ActivityLogId");

                            b1.HasIndex("Id")
                                .HasDatabaseName("IX_ActivityLogs_TargetId");

                            b1.ToTable("ActivityLogs");

                            b1.WithOwner()
                                .HasForeignKey("ActivityLogId");
                        });

                    b.Navigation("Actor")
                        .IsRequired();

                    b.Navigation("Target")
                        .IsRequired();
                });

            modelBuilder.Entity("Logging.Domain.Entities.LogChange", b =>
                {
                    b.HasOne("Logging.Domain.Entities.ActivityLog", "ActivityLog")
                        .WithMany("Changes")
                        .HasForeignKey("ActivityLogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActivityLog");
                });

            modelBuilder.Entity("Logging.Domain.Entities.ActivityLog", b =>
                {
                    b.Navigation("Changes");
                });
#pragma warning restore 612, 618
        }
    }
}
